version: "3"
services:
  app:
    build:
      context: ../
      dockerfile: docker-release/app/Dockerfile
    image: ***REMOVED***/***REMOVED***/iass:1.0.4-app
    network_mode: "host"
    # アプリケーションファイルはコンテナレイヤーで追加
    #volumes:
    #  - ../in_iass:/var/www/in_iass
    #  - ../in_auth:/var/www/in_auth
    environment:
      - DB_HOST=127.0.0.1
      - HTTP_S_DOMAIN=***REMOVED***
      - HTTP_SCHEMA=http
  web:
    build:
      context: ../
      dockerfile: docker-release/web/Dockerfile
    image: ***REMOVED***/***REMOVED***/iass:1.0.3-web
    network_mode: "host"
    ports:
     - "80:80"
    # アプリケーションファイルはコンテナレイヤーで追加
    #volumes:
    #  - ../in_iass:/var/www/in_iass
    #  - ../in_auth:/var/www/in_auth
    depends_on:
     - app
  # DBコンテナを追加しない
  #db:
  #  build:
  #    context: ../
  #    dockerfile: docker-release/db/Dockerfile
  #  network_mode: "host"
  #  environment:
  #    - MARIADB_ROOT_PASSWORD=dev
