version: "3"
services:
  app:
    build:
      context: ../
      dockerfile: docker/app/Dockerfile
    network_mode: "host"
    volumes:
      - ../in_iass:/var/www/in_iass
      - ../in_auth:/var/www/in_auth
    environment:
      - DB_HOST=127.0.0.1
      - HTTP_S_DOMAIN=***REMOVED***
      - HTTP_SCHEMA=http
  web:
    build:
      context: ../
      dockerfile: docker/web/Dockerfile
    network_mode: "host"
    ports:
     - "80:80"
    volumes:
     - ../in_iass:/var/www/in_iass
     - ../in_auth:/var/www/in_auth
    depends_on:
     - app
  db:
    build:
      context: ../
      dockerfile: docker/db/Dockerfile
    network_mode: "host"
    environment:
      - MARIADB_ROOT_PASSWORD=dev
